-- PlanVistaテーブル作成

-- ユーザーテーブル
CREATE TABLE IF NOT EXISTS users(
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    username VARCHAR(10) NOT NULL COMMENT 'ユーザー名',
    email VARCHAR(30) NOT NULL COMMENT 'メールアドレス',
    password VARCHAR(30) NOT NULL COMMENT 'パスワード',
    company_id VARCHAR(10) NOT NULL COMMENT '所属ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE=InnoDB

COMMENT='ユーザーテーブル';

-- スケジュールテーブル
CREATE TABLE IF NOT EXISTS schedules(
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    user_id VARCHAR(10) NOT NULL COMMENT 'ユーザーID',
    schedule_name VARCHAR(30) NOT NULL COMMENT 'スケジュール名',
    task VARCHAR(30) NOT NULL COMMENT 'タスク名',
    start_time DATETIME NOT NULL COMMENT '開始時間',
    end_time DATETIME NOT NULL COMMENT '終了時間',
    task_time TIME NOT NULL COMMENT '所要時間',
    memo VARCHAR(255) COMMENT 'メモ',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    deleted_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '削除日時'
) ENGINE=InnoDB

COMMENT='スケジュールテーブル';

-- レコードテーブル
CREATE TABLE IF NOT EXISTS records(
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    user_id VARCHAR(10) NOT NULL COMMENT 'ユーザーID',
    task VARCHAR(30) NOT NULL COMMENT 'タスク名',
    start_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '開始時間',
    end_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '終了時間',
    task_time TIME NOT NULL COMMENT '所要時間',
    memo VARCHAR(255) COMMENT 'メモ',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    deleted_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '削除日時'
) ENGINE=InnoDB

COMMENT='レコードテーブル';

-- 管理者テーブル
CREATE TABLE IF NOT EXISTS companies(
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    name VARCHAR(10) NOT NULL COMMENT '会社名',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE=InnoDB

COMMENT='レコードテーブル';
